### ISSUE TITLE
Instance Flavor Billing

### ISSUE THREAD

**Issue by lapnd** [Yuyu-billing/yuyu#6]
Hi,
As I read on [document](https://yuyu-billing.dev/introduction/), there is a rule to count for billing as Instance Flavor:

> You can set the price for each Flavor that you have. Each instance that uses a flavor will be counted for Billing. You still be charged for instance even if the instance is stopped unless you delete it.

It seems inflexible to user since when users stop instance, they expected to save the cost (for example, stopping VM on the weekend and start it again on working days)

Can you please tell me the reason why we still have to count even when user stops VM?
Thank you!

**Comment by irfanpule** [comment]
Hi @lapnd 
We start yuyu with MVP like that. MVP yuyu refers to openstack as a private cloud. Usually, what we know is that private clouds rarely start and stop because they feel that the cloud is theirs. But this case has been included in our next feature development list.

**Comment by lapnd** [comment]
Thank you @irfanpule
